name: diametics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  fl_chart: ^0.70.1
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  openfoodfacts: ^3.20.0
  shared_preferences: ^2.5.2
  flutter_cache_manager: ^3.4.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  mobile_scanner: ^6.0.7
  url_launcher: ^6.3.1
  mockito: ^5.4.5
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  provider: ^6.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/DiaMetics.png
    - assets/GIcon.png
    - assets/profile.png
    - assets/yoga.png
    - assets/lifiting.png
    - assets/running.png
    - assets/food.jpg
    - assets/RecipePic.png
    - assets/avocado.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
