// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQ_EwoOyFFra1P55VM2lrQ7v-PR_En8w',
    appId: '1:862563017151:web:370f3d5a891a96e35f810a',
    messagingSenderId: '862563017151',
    projectId: 'diametics-90bd8',
    authDomain: 'diametics-90bd8.firebaseapp.com',
    storageBucket: 'diametics-90bd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNLgVr3BvkBqXPOeb78LH5IQ16yQb2tus',
    appId: '1:862563017151:android:cc13d349f94434e35f810a',
    messagingSenderId: '862563017151',
    projectId: 'diametics-90bd8',
    storageBucket: 'diametics-90bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCz7ICrvvsVj7t3oAr6O6DOtC7NhvGDY',
    appId: '1:862563017151:ios:fdf9ef5bb6dd86f25f810a',
    messagingSenderId: '862563017151',
    projectId: 'diametics-90bd8',
    storageBucket: 'diametics-90bd8.firebasestorage.app',
    iosBundleId: 'com.example.diametics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCz7ICrvvsVj7t3oAr6O6DOtC7NhvGDY',
    appId: '1:862563017151:ios:fdf9ef5bb6dd86f25f810a',
    messagingSenderId: '862563017151',
    projectId: 'diametics-90bd8',
    storageBucket: 'diametics-90bd8.firebasestorage.app',
    iosBundleId: 'com.example.diametics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQ_EwoOyFFra1P55VM2lrQ7v-PR_En8w',
    appId: '1:862563017151:web:3e1c8d011bcd4a9c5f810a',
    messagingSenderId: '862563017151',
    projectId: 'diametics-90bd8',
    authDomain: 'diametics-90bd8.firebaseapp.com',
    storageBucket: 'diametics-90bd8.firebasestorage.app',
  );
}
